# Generated by Django 2.0.5 on 2018-05-15 08:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='media/supervise/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='media/supervise/')),
                ('correct_dep', models.CharField(max_length=50)),
                ('correct_person', models.CharField(max_length=20)),
                ('correction', models.TextField(blank=True, null=True)),
                ('correct_date', models.DateField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('remark', models.CharField(max_length=100)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supervise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddate', models.DateField()),
                ('county', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('contact', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=20)),
                ('community', models.CharField(max_length=50)),
                ('grid', models.CharField(max_length=20)),
                ('grid_person', models.CharField(max_length=20)),
                ('checker', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/supervise/')),
                ('is_correct', models.BooleanField(default=False)),
                ('remark', models.CharField(max_length=100)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='defect',
            name='supervise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervise', to='supervise.Supervise'),
        ),
    ]
