# Generated by Django 2.0.5 on 2018-05-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defect',
            name='correct_date',
        ),
        migrations.RemoveField(
            model_name='defect',
            name='correct_dep',
        ),
        migrations.RemoveField(
            model_name='defect',
            name='correct_person',
        ),
        migrations.AddField(
            model_name='supervise',
            name='correct_duty_dep',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervise',
            name='correct_duty_person',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='defect',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supervise',
            name='grid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supervise',
            name='grid_person',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supervise',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
