# Generated by Django 2.0.5 on 2018-05-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervise', '0002_auto_20180516_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervise',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='supervise',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitde'),
        ),
    ]
