# Generated by Django 2.0.5 on 2018-05-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervise', '0003_auto_20180516_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervise',
            name='correct_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
