# Generated by Django 2.0.5 on 2018-05-28 08:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supervise', '0004_supervise_correct_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='media/defect/')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect', to='supervise.Defect')),
            ],
        ),
        migrations.CreateModel(
            name='DefectCorrectAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='media/defect/')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect2', to='supervise.Defect')),
            ],
        ),
    ]
