export const FETCH_SUPERVISES = 'FETCH_SUPERVISES';
export const NEW_SUPERVISE = 'NEW_SUPERVISE';
export const FETCH_SUPERVISE = 'FETCH_SUPERVISE';
export const DELETE_SUPERVISE = 'DELETE_SUPERVISE';
export const EDIT_SUPERVISE = 'EDIT_SUPERVISE';

export const FETCH_DEFECTS = 'FETCH_DEFECTS';
export const FETCH_DEFECT = 'FETCH_DEFECT';
export const FETCH_DEFECTS_BY_SUPERVISE = 'FETCH_DEFECTS_BY_SUPERVISE';
export const NEW_DEFECT = 'NEW_DEFECT';
export const EDIT_DEFECT = 'EDIT_DEFECT';
export const DELETE_DEFECT = 'DELETE_DEFECT';
export const NEW_DEFECT_ATTACHMENT = 'NEW_DEFECT_ATTACHMENT';
export const GET_DEFECT_ATTACHMENTS_BY_SUPERVISE = 'GET_DEFECT_ATTACHMENTS_BY_SUPERVISE';

export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';


export const UURL = 'http://localhost:8000/'